server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:sqlite:C:/Users/lenovlo/Documents/Laptop Backup/Cdac/workspaces/Databases/Java microservices/Hotel Service/hotelservice.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
    
    
    
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-44569240.okta.com/oauth2/default
    
    
    
  jpa:
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
    
